name: Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.config/yarn/global
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Yarn
      run: |
        npm install -g yarn
        yarn install

    - name: Run ESLint
      run: yarn test:lint
